sudo: required

services:
  - docker

install:
  - docker-compose build --no-cache
  - docker-compose up -d

script:
  - docker exec -it foodcare-web ng test --watch=false

after_script:
  - docker-compose down
