version: "3.1"
services:
  foodcare-web:
    container_name: foodcare-web
    restart: always
    image: frontend:latest
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/foodcare-web
      - /foodcare-web/node_modules
    command: ng serve --host 0 --port 4200
