version: "3.0"
services:
  foodcare-web:
    container_name: foodcare-web
    build: ./
    volumes:
      - './:/app/foodcare-web'
      - '/app/foodcare-web/node_modules'
    ports:
      - "4200:4200"
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
