version: "0.1"
services:
  foodcare-web:
    build: ./
    volumes:
      - ./:/app/foodcare-web
    ports:
      - "4200:4200"
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
